pipeline {
agent any


stages {

    stage('Check Java') {
        steps {
            sh '''
            java -version
            javac -version
            mvn -version
            '''
        }
    }

    stage('Build Maven') {
        steps {
            dir('Project/src') {
                sh 'mvn clean package'
            }
        }
    }
}

}
