pipeline {
agent any

stages {

    stage('Check Java') {
        steps {
            sh '''
            echo "JAVA_HOME=$JAVA_HOME"
            which java
            which javac

            java -version
            javac -version
            mvn -version
            '''
        }
    }

}

}
